### ISSUE TITLE
ERROR: for postgres  Cannot create container for service postgres: Invalid bind mount spec

### ISSUE THREAD

**Issue by kareem3d** [kriasoft/nodejs-api-starter#17] opened 2017-01-07 08:10 UTC
I get this error on my windows machine when trying to run `docker-compose up`

```
ERROR: for postgres  Cannot create container for service postgres: Invalid bind mount spec "C:\\playground\\example-api\\scripts\\postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:rw": Invalid volume specification: 'C:\playground\example-api\scripts\postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:rw'
ERROR: Encountered errors while bringing up the project.
```

**Comment by koistya** [comment] 2017-01-07 09:09
@kareem3d in `docker-compose.yml` there is a line:

```yml
      - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh
```

..telling Docker to mount `./scripts/postgres-init.sh` file inside `postgres` container at this location - `/docker-entrypoint-initdb.d/init.sh`. Can you double-check that the file `C:\playground\example-api\scripts\postgres-init.sh` actually exists on disk? You can also tweak this mount point to be read-only by appending `:ro` at the end:

```yml
      - ./scripts/postgres-init.sh:/docker-entrypoint-initdb.d/init.sh:ro
```

...also, do you use the latest version of **Docker for Windows**? You can try to restart Docker. Or, run `docker-compose down` and then `docker-compose up` again.. or, see the list of created volumes by running `docker volume ls` and remove volumes that you don't need with `docker volume rm <name>`, then run `docker-compose up` again.. Does any of this help to solve the issue?

**Comment by kareem3d** [comment] 2017-01-07 12:16
@koistya Still no luck :( , That's what I have tried
- I made sure the `postgres-init.sh` file exists
- I added the `:ro` at the end then ran `docker-compose down`, removed all volumes and ran `docker-compose up` again

I'm installing this boilerplate to just play around with graphql so probably I will remove all postgres db code and try to run again without it, that should fix the problem

**Comment by koistya** [comment] 2017-01-07 17:08
@kareem3d another thing you could try is to enclose Windows path in quotes:

```yml
      - "./scripts/postgres-init.sh":/docker-entrypoint-initdb.d/init.sh
```

Ref https://github.com/docker/compose/issues/2487

**Comment by koistya** [comment] 2017-04-02 12:50
Sorry, cannot reproduce. If anyone else is having the same issue, please re-open. Closing for now.

**Closed by koistya** 2017-04-02 12:50 UTC

**Comment by rocinante42** [comment] 2017-04-05 22:35
I'm having related issue but it says:
 `ERROR: for db Cannot create container for service db: invalid bind mount spec`

**Comment by rocinante42** [comment] 2017-04-05 22:44
`ERROR: for db  Cannot create container for service db: invalid bind mount spec "C:\\users\\r300\\documents\\kelsus\\api\
\server\\config\\postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:rw": invalid volume specification: 'C:\users\r
300\documents\kelsus\api\server\config\postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:rw'
ERROR: Encountered errors while bringing up the project.`

**Comment by koistya** [comment] 2017-04-06 07:15
@rocinante42 are you using the latest version of [Docker for Windows](https://docs.docker.com/docker-for-windows/)?

```sh
PS C:\Users\Docker> docker --version
Docker version 17.03.0-ce, build 60ccb22

PS C:\Users\Docker> docker-compose --version
docker-compose version 1.11.2, build dfed245

PS C:\Users\Docker> docker-machine --version
docker-machine version 0.10.0, build 76ed2a6
```

You may also want to check Docker for Windows > [FAQ](https://docs.docker.com/docker-for-windows/faqs/) and [Troubleshooting](https://docs.docker.com/docker-for-windows/troubleshoot/) sections. For example, Docker for Windows doesn't support file events in mounted volumes, which prevents "live reload" from working (with default settings), in that case, you would need to set `CHOKIDAR_USEPOLLING=true` environment variable as a workaround by creating `docker-compose.override.yml` file in the root of your project with the following content:

```yml
version: '3'
services:
  api:
    environment:
      - CHOKIDAR_USEPOLLING=false
```

This project works fine for me on Windows. Not sure how to replicate this issue. I see there is an extra space in the path `\\api\ \server\\`.. maybe that's the issue?
